name: Build and Package Rust Program

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
            - os: ubuntu-latest
              triple: x86_64-unknown-linux-gnu
              name: linux
            - os: macos-latest
              triple: x86_64-apple-darwin
              name: mac-x86-64
            - os: macos-latest
              triple: aarch64-apple-darwin
              name: mac-arm64

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Rust
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    # Install Rust target (if not native)
    - name: Add target for cross-compilation
      run: rustup target add ${{ matrix.target.triple }}

    # Cache Cargo dependencies
    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # Build the project in release mode
    - name: Build project
      run: cargo build --release --target=${{ matrix.target.triple }}

    # Package the binary as an artifact
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: procnotify-${{ matrix.target.name }}
        path: target/${{ matrix.target }}/release/procnotify
